import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Inter, Space_Grotesk } from 'next/font/google';
import { Box, CssBaseline } from '@mui/material';

// Providers
import { ThemeAppProvider } from '@/providers/ThemeAppProvider';
import { NotistackProvider } from '@/providers/NotistackProvider';

import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '700', '800', '900'],
  variable: '--font-inter'
});

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  variable: '--font-grotesk'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className={`${inter.className} ${spaceGrotesk.variable}`}>
        <AppRouterCacheProvider>
          <ThemeAppProvider>
            <CssBaseline />
            <Box
              sx={{
                height: '100%',
                width: '100%'
              }}
            >
              <NotistackProvider>{children}</NotistackProvider>
            </Box>
          </ThemeAppProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
